//
// JSON Schema Tests
// Tests JSON Schema for IDE autocomplete support
//

#include <doctest/doctest.h>

#ifdef ONYXUI_ENABLE_YAML_THEMES

#include <rfl.hpp>
#include <rfl/json.hpp>
#include <onyxui/theme.hh>
#include <onyxui/conio/conio_backend.hh>
#include <test_config.hh>  // Generated by CMake with test data paths
#include <fstream>
#include <filesystem>

TEST_CASE("JSON Schema - Schema file validation") {
    SUBCASE("Schema file exists and is valid JSON") {
        // The schema file path is provided by CMake-generated config
        // Schema file is in unittest/testdata/schemas/ (not in include/)
        std::filesystem::path schema_path(test::config::CONIO_THEME_SCHEMA);

        CHECK(std::filesystem::exists(schema_path));

        if (std::filesystem::exists(schema_path)) {
            // Read the schema file
            std::ifstream file(schema_path);
            std::string schema_content((std::istreambuf_iterator<char>(file)),
                                      std::istreambuf_iterator<char>());

            // Schema should not be empty
            CHECK(!schema_content.empty());

            // Trim trailing whitespace
            while (!schema_content.empty() && std::isspace(schema_content.back())) {
                schema_content.pop_back();
            }

            // Schema should be valid JSON
            CHECK(schema_content.front() == '{');
            CHECK(schema_content.back() == '}');

            // Check for balanced braces (simple JSON validation)
            int brace_count = 0;
            for (char c : schema_content) {
                if (c == '{') brace_count++;
                if (c == '}') brace_count--;
            }
            CHECK(brace_count == 0);
        }
    }

    SUBCASE("Schema structure validation") {
        std::filesystem::path schema_path(test::config::CONIO_THEME_SCHEMA);

        if (std::filesystem::exists(schema_path)) {
            std::ifstream file(schema_path);
            std::string schema((std::istreambuf_iterator<char>(file)),
                              std::istreambuf_iterator<char>());

            // JSON Schema should contain standard fields
            CHECK(schema.find("\"$schema\"") != std::string::npos);
            CHECK(schema.find("\"definitions\"") != std::string::npos);
            CHECK(schema.find("\"properties\"") != std::string::npos);
            CHECK(schema.find("\"type\"") != std::string::npos);
        }
    }
}

TEST_CASE("JSON Schema - Copy schema to themes directory") {
    SUBCASE("Copy schema to themes directory for IDE use") {
        // Read the source schema
        std::filesystem::path schema_path(test::config::CONIO_THEME_SCHEMA);

        if (std::filesystem::exists(schema_path)) {
            std::ifstream source_file(schema_path);
            std::string schema_content((std::istreambuf_iterator<char>(source_file)),
                                      std::istreambuf_iterator<char>());

            // Create test directory
            std::filesystem::path test_dir = std::filesystem::temp_directory_path() / "onyxui_schema_test";
            std::filesystem::create_directories(test_dir);

            // Write schema to test themes directory
            std::filesystem::path dest_file = test_dir / "conio-theme.schema.json";
            std::ofstream dest(dest_file);
            dest << schema_content;
            dest.close();

            // Verify file exists and has content
            CHECK(std::filesystem::exists(dest_file));
            CHECK(std::filesystem::file_size(dest_file) > 0);

            // Read back and verify it's the same
            std::ifstream read_file(dest_file);
            std::string content((std::istreambuf_iterator<char>(read_file)),
                               std::istreambuf_iterator<char>());
            CHECK(content == schema_content);

            // Cleanup
            std::filesystem::remove_all(test_dir);
        } else {
            // If schema file not found, mark test as passed but note it
            CHECK(true); // Test passes but schema not found
        }
    }
}

TEST_CASE("JSON Schema - Schema content verification") {
    SUBCASE("Schema contains theme fields") {
        std::filesystem::path schema_path(test::config::CONIO_THEME_SCHEMA);

        if (std::filesystem::exists(schema_path)) {
            std::ifstream file(schema_path);
            std::string schema((std::istreambuf_iterator<char>(file)),
                              std::istreambuf_iterator<char>());

            // Schema should mention key theme fields
            // These are the top-level properties in ui_theme
            CHECK(schema.find("\"name\"") != std::string::npos);
            CHECK(schema.find("\"button\"") != std::string::npos);
            CHECK(schema.find("\"label\"") != std::string::npos);
            CHECK(schema.find("\"panel\"") != std::string::npos);

            // Schema should define color type
            CHECK(schema.find("\"color\"") != std::string::npos);

            // Schema should define font type
            CHECK(schema.find("\"font\"") != std::string::npos);

            // Schema should define enums
            CHECK(schema.find("\"box_style\"") != std::string::npos);
            CHECK(schema.find("\"horizontal_alignment\"") != std::string::npos);
        }
    }
}

#else // !ONYXUI_ENABLE_YAML_THEMES

TEST_CASE("JSON Schema - YAML themes disabled") {
    CHECK(true);
}

#endif // ONYXUI_ENABLE_YAML_THEMES
