/**
 * @file xpm_parser.hh
 * @brief XPM (X PixMap) image parser for loading retro icons
 *
 * Supports XPM3 format as used by Windows 3.11 theme assets.
 * Parses XPM data into a pixel buffer that can be converted to SDL textures.
 */

#pragma once

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>
#include <unordered_map>
#include <optional>
#include <array>

namespace onyxui::sdlpp {

/**
 * @struct xpm_color
 * @brief RGBA color with transparency support
 */
struct xpm_color {
    std::uint8_t r = 0;
    std::uint8_t g = 0;
    std::uint8_t b = 0;
    std::uint8_t a = 255;  // 0 = transparent (None)

    [[nodiscard]] constexpr bool is_transparent() const noexcept {
        return a == 0;
    }
};

/**
 * @class xpm_image
 * @brief Parsed XPM image with pixel data
 */
class xpm_image {
public:
    xpm_image() = default;

    /**
     * @brief Parse XPM data from C-style string array
     * @param data XPM data array (as generated by XPM files)
     * @return Parsed image, or nullopt on parse error
     */
    static std::optional<xpm_image> parse(const char* const* data);

    /**
     * @brief Parse XPM data from string
     * @param xpm_string Complete XPM file content as string
     * @return Parsed image, or nullopt on parse error
     */
    static std::optional<xpm_image> parse_string(std::string_view xpm_string);

    [[nodiscard]] int width() const noexcept { return m_width; }
    [[nodiscard]] int height() const noexcept { return m_height; }

    /**
     * @brief Get pixel color at position
     * @param x X coordinate (0 to width-1)
     * @param y Y coordinate (0 to height-1)
     * @return Pixel color
     */
    [[nodiscard]] xpm_color pixel(int x, int y) const noexcept {
        if (x < 0 || x >= m_width || y < 0 || y >= m_height) {
            return {};  // Transparent black for out of bounds
        }
        return m_pixels[static_cast<std::size_t>(y * m_width + x)];
    }

    /**
     * @brief Get raw pixel data as RGBA buffer
     * @return Pointer to RGBA pixel data (4 bytes per pixel)
     */
    [[nodiscard]] const std::uint8_t* rgba_data() const noexcept {
        return reinterpret_cast<const std::uint8_t*>(m_pixels.data());
    }

    /**
     * @brief Get pixel data size in bytes
     */
    [[nodiscard]] std::size_t data_size() const noexcept {
        return m_pixels.size() * sizeof(xpm_color);
    }

    [[nodiscard]] bool empty() const noexcept {
        return m_pixels.empty();
    }

private:
    int m_width = 0;
    int m_height = 0;
    std::vector<xpm_color> m_pixels;

    /**
     * @brief Parse hex color string (#RRGGBB or #RGB)
     */
    static std::optional<xpm_color> parse_hex_color(std::string_view hex);
};

// ============================================================================
// Embedded Windows 3.11 XPM Icons
// ============================================================================

namespace win311_icons {

// Window control buttons (16x16)
extern const char* const close_active[];
extern const char* const close_inactive[];
extern const char* const minimize_active[];
extern const char* const minimize_inactive[];
extern const char* const maximize_active[];
extern const char* const maximize_inactive[];
extern const char* const restore_active[];
extern const char* const restore_inactive[];
extern const char* const menu_active[];
extern const char* const menu_inactive[];

// Checkbox icons (13x13 - standard Win3.11 size)
extern const char* const checkbox_unchecked[];
extern const char* const checkbox_checked[];
extern const char* const checkbox_indeterminate[];
extern const char* const checkbox_unchecked_disabled[];
extern const char* const checkbox_checked_disabled[];

// Radio button icons (16x16)
extern const char* const radio_unchecked[];
extern const char* const radio_checked[];
extern const char* const radio_unchecked_disabled[];
extern const char* const radio_checked_disabled[];

// Scrollbar arrows (16x16)
extern const char* const arrow_up[];
extern const char* const arrow_down[];
extern const char* const arrow_left[];
extern const char* const arrow_right[];
extern const char* const arrow_up_disabled[];
extern const char* const arrow_down_disabled[];
extern const char* const arrow_left_disabled[];
extern const char* const arrow_right_disabled[];

} // namespace win311_icons

} // namespace onyxui::sdlpp
