/**
 * @file test_event_target_comprehensive.cc
 * @brief Comprehensive tests for event_target event processing
 *
 * Tests the event_target class's event processing pipeline, including:
 * - Mouse button click generation (press + release = click)
 * - Event concept priority (button events before position events)
 * - Mouse enter/leave tracking
 * - State management (hover, pressed, focus)
 * - Event handler callbacks
 */

#include "onyxui/concepts/event_like.hh"
#include <doctest/doctest.h>
#include <../../include/onyxui/core/event_target.hh>
#include <utils/test_backend.hh>

using namespace onyxui;

// Helper to convert test backend events to ui_event
inline ui_event make_mouse_event(int x, int y, bool pressed, int button = 1) {
    mouse_event evt;
    evt.x = logical_unit(static_cast<double>(x));
    evt.y = logical_unit(static_cast<double>(y));
    evt.btn = (button == 1) ? mouse_event::button::left :
              (button == 2) ? mouse_event::button::middle :
              (button == 3) ? mouse_event::button::right :
              mouse_event::button::none;
    evt.act = pressed ? mouse_event::action::press : mouse_event::action::release;
    return ui_event{evt};
}

// Helper for mouse move events
inline ui_event make_mouse_move(int x, int y) {
    mouse_event evt;
    evt.x = logical_unit(static_cast<double>(x));
    evt.y = logical_unit(static_cast<double>(y));
    evt.btn = mouse_event::button::none;
    evt.act = mouse_event::action::move;
    return ui_event{evt};
}

// ======================================================================
// Test Helper: Concrete event_target implementation for testing
// ======================================================================

class test_event_target_comprehensive : public event_target<test_backend> {
public:
    // Track which handlers were called
    int enter_count = 0;
    int leave_count = 0;
    int move_count = 0;
    int down_count = 0;
    int up_count = 0;
    int click_count = 0;

    // Last event details
    logical_unit last_x = -1.0_lu;
    logical_unit last_y = -1.0_lu;
    int last_button = -1;

    // Define hit testing bounds
    logical_unit bounds_x = 0.0_lu;
    logical_unit bounds_y = 0.0_lu;
    logical_unit bounds_w = 100.0_lu;
    logical_unit bounds_h = 50.0_lu;

    // Implement required abstract method
    [[nodiscard]] bool is_inside(logical_unit x, logical_unit y) const override {
        return x >= bounds_x && x < (bounds_x + bounds_w) &&
               y >= bounds_y && y < (bounds_y + bounds_h);
    }

protected:
    // Override handle_mouse to track events
    bool handle_mouse(const mouse_event& mouse) override {
        // Track hover changes via is_hovered() state
        bool const was_hovered = this->is_hovered();

        // Let base class handle the event
        bool handled = event_target::handle_mouse(mouse);

        // Detect state changes
        bool const now_hovered = this->is_hovered();
        if (now_hovered && !was_hovered) {
            enter_count++;
        } else if (!now_hovered && was_hovered) {
            leave_count++;
        }

        // Check if event is inside bounds (for counting purposes)
        bool const in_bounds = is_inside(mouse.x, mouse.y);

        // Track specific actions
        // Old API behavior: press only counted if inside, release counted if pressed
        switch (mouse.act) {
            case mouse_event::action::press:
                if (in_bounds) {
                    down_count++;
                    last_x = mouse.x;
                    last_y = mouse.y;
                    last_button = static_cast<int>(mouse.btn);
                }
                break;

            case mouse_event::action::release:
                // Old API: release handler called if widget was pressed (even if release outside)
                if (was_hovered || this->is_pressed()) {
                    up_count++;
                    last_x = mouse.x;
                    last_y = mouse.y;
                    last_button = static_cast<int>(mouse.btn);
                }
                // Click generated by base class if press+release both inside
                if (handled) {
                    click_count++;
                }
                break;

            case mouse_event::action::move:
                // Old API: only count moves while already hovered (not the first move that triggers enter)
                if (was_hovered && now_hovered) {
                    move_count++;
                    last_x = mouse.x;
                    last_y = mouse.y;
                }
                break;

            case mouse_event::action::wheel_up:
            case mouse_event::action::wheel_down:
                break;
        }

        return handled;
    }
};

// ======================================================================
// Mouse Button Click Generation Tests
// ======================================================================

// Verify concept satisfaction at compile time
static_assert(MousePositionEvent<test_backend::test_mouse_event>, "test_mouse_event must satisfy MousePositionEvent");
static_assert(MouseButtonEvent<test_backend::test_mouse_event>, "test_mouse_event must satisfy MouseButtonEvent");

TEST_SUITE("EventTarget - Mouse Click Generation") {
    TEST_CASE("Press inside + Release inside = Click generated") {
        test_event_target_comprehensive target;

        // Press button inside
        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);
        CHECK(target.down_count == 1);
        CHECK(target.is_pressed());

        // Release button inside
        target.handle_event(make_mouse_event(50, 25, false), event_phase::target);
        CHECK(target.up_count == 1);
        CHECK(target.click_count == 1);  // ✅ Click generated!
        CHECK_FALSE(target.is_pressed());
    }

    TEST_CASE("Press outside = No click generated") {
        test_event_target_comprehensive target;

        // Press button outside bounds
        target.handle_event(make_mouse_event(200, 25, true), event_phase::target);
        CHECK(target.down_count == 0);  // Not called
        CHECK_FALSE(target.is_pressed());

        // Release inside
        target.handle_event(make_mouse_event(50, 25, false), event_phase::target);
        CHECK(target.click_count == 0);  // ❌ No click (press was outside)
    }

    TEST_CASE("Press inside + Release outside = No click generated") {
        test_event_target_comprehensive target;

        // Press button inside
        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);
        CHECK(target.down_count == 1);
        CHECK(target.is_pressed());

        // Release button outside
        target.handle_event(make_mouse_event(200, 25, false), event_phase::target);
        CHECK(target.up_count == 1);  // Still called
        CHECK(target.click_count == 0);  // ❌ No click (release outside)
    }

    TEST_CASE("Multiple clicks") {
        test_event_target_comprehensive target;

        // First click
        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);
        target.handle_event(make_mouse_event(50, 25, false), event_phase::target);

        CHECK(target.click_count == 1);

        // Second click
        target.handle_event(make_mouse_event(60, 30, true), event_phase::target);
        target.handle_event(make_mouse_event(60, 30, false), event_phase::target);

        CHECK(target.click_count == 2);  // ✅ Two clicks
    }

    TEST_CASE("Different mouse buttons") {
        test_event_target_comprehensive target;

        SUBCASE("Left button") {
            target.handle_event(make_mouse_event(50, 25, true, 1), event_phase::target);
            target.handle_event(make_mouse_event(50, 25, false, 1), event_phase::target);

            CHECK(target.click_count == 1);
            CHECK(target.last_button == static_cast<int>(mouse_event::button::left));
        }

        SUBCASE("Right button") {
            target.handle_event(make_mouse_event(50, 25, true, 3), event_phase::target);
            target.handle_event(make_mouse_event(50, 25, false, 3), event_phase::target);

            CHECK(target.click_count == 1);
            CHECK(target.last_button == static_cast<int>(mouse_event::button::right));
        }
    }
}

// ======================================================================
// Event Concept Priority Tests (THE CRITICAL BUG!)
// ======================================================================

TEST_SUITE("EventTarget - Event Concept Priority") {
    TEST_CASE("MouseButtonEvent has priority over MousePositionEvent") {
        test_event_target_comprehensive target;

        SUBCASE("Button press is NOT treated as move event") {
            // Process event - should be treated as button event, NOT move!
            target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

            CHECK(target.down_count == 1);     // ✅ Mouse down called
            CHECK(target.move_count == 0);     // ❌ Mouse move NOT called
            CHECK(target.is_pressed());
        }

        SUBCASE("Button release is NOT treated as move event") {
            // First press
            target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

            // Then release
            target.handle_event(make_mouse_event(50, 25, false), event_phase::target);

            CHECK(target.up_count == 1);      // ✅ Mouse up called
            CHECK(target.click_count == 1);   // ✅ Click generated
            CHECK(target.move_count == 0);    // ❌ Move still NOT called
        }

        SUBCASE("Full click sequence generates no move events") {
            // Press
            target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

            // Release
            target.handle_event(make_mouse_event(50, 25, false), event_phase::target);

            // Verify: down + up + click, but NO move
            CHECK(target.down_count == 1);
            CHECK(target.up_count == 1);
            CHECK(target.click_count == 1);
            CHECK(target.move_count == 0);  // Critical: no move events!
        }
    }
}

// ======================================================================
// Mouse Enter/Leave Tests
// ======================================================================

TEST_SUITE("EventTarget - Mouse Enter/Leave") {
    TEST_CASE("Mouse enter when moving into bounds") {
        test_event_target_comprehensive target;

        // Move mouse outside bounds
        target.handle_event(make_mouse_move(200, 25), event_phase::target);
        CHECK(target.enter_count == 0);
        CHECK_FALSE(target.is_hovered());

        // Move mouse inside bounds
        target.handle_event(make_mouse_move(50, 25), event_phase::target);
        CHECK(target.enter_count == 1);  // ✅ Enter event!
        CHECK(target.is_hovered());
    }

    TEST_CASE("Mouse leave when moving out of bounds") {
        test_event_target_comprehensive target;

        // Start inside
        target.handle_event(make_mouse_move(50, 25), event_phase::target);

        CHECK(target.enter_count == 1);
        CHECK(target.is_hovered());

        // Move outside
        target.handle_event(make_mouse_move(200, 25), event_phase::target);

        CHECK(target.leave_count == 1);  // ✅ Leave event!
        CHECK_FALSE(target.is_hovered());
    }

    TEST_CASE("No enter/leave when staying inside") {
        test_event_target_comprehensive target;

        // Move to position 1 inside
        target.handle_event(make_mouse_move(50, 25), event_phase::target);

        CHECK(target.enter_count == 1);

        // Move to position 2 inside (still inside!)
        target.handle_event(make_mouse_move(60, 30), event_phase::target);

        // Still only 1 enter, no leave
        CHECK(target.enter_count == 1);
        CHECK(target.leave_count == 0);
        CHECK(target.move_count == 1);  // Only pos2 triggers move (pos1 triggers enter)
    }
}

// ======================================================================
// State Management Tests
// ======================================================================

TEST_SUITE("EventTarget - State Management") {
    TEST_CASE("Pressed state tracking") {
        test_event_target_comprehensive target;

        CHECK_FALSE(target.is_pressed());

        // Press
        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

        CHECK(target.is_pressed());

        // Release
        target.handle_event(make_mouse_event(50, 25, false), event_phase::target);

        CHECK_FALSE(target.is_pressed());
    }

    TEST_CASE("Hovered state tracking") {
        test_event_target_comprehensive target;

        CHECK_FALSE(target.is_hovered());

        // Move inside
        target.handle_event(make_mouse_move(50, 25), event_phase::target);

        CHECK(target.is_hovered());

        // Move outside
        target.handle_event(make_mouse_move(200, 25), event_phase::target);

        CHECK_FALSE(target.is_hovered());
    }

    TEST_CASE("Disabled target doesn't process events") {
        test_event_target_comprehensive target;
        target.set_enabled(false);

        // Try to click
        bool const handled = target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

        CHECK_FALSE(handled);
        CHECK(target.down_count == 0);  // Not called!
        CHECK_FALSE(target.is_pressed());
    }

    TEST_CASE("Re-enabling target allows events") {
        test_event_target_comprehensive target;
        target.set_enabled(false);
        target.set_enabled(true);

        // Click should work now
        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);

        CHECK(target.down_count == 1);  // Event was processed!
        CHECK(target.is_pressed());
    }
}

// ======================================================================
// Edge Cases
// ======================================================================

TEST_SUITE("EventTarget - Edge Cases") {
    TEST_CASE("Rapid press/release") {
        test_event_target_comprehensive target;

        // Rapidly click 10 times
        for (int i = 0; i < 10; i++) {
            target.handle_event(make_mouse_event(50, 25, true), event_phase::target);
            target.handle_event(make_mouse_event(50, 25, false), event_phase::target);
        }

        CHECK(target.click_count == 10);
    }

    TEST_CASE("Press without release doesn't crash") {
        test_event_target_comprehensive target;

        target.handle_event(make_mouse_event(50, 25, true), event_phase::target);
        CHECK(target.is_pressed());

        // Never release - state should persist
        CHECK(target.is_pressed());
    }

    TEST_CASE("Boundary coordinates") {
        test_event_target_comprehensive target;
        target.bounds_x = 0.0_lu;
        target.bounds_y = 0.0_lu;
        target.bounds_w = 100.0_lu;
        target.bounds_h = 50.0_lu;

        SUBCASE("Top-left corner") {
            target.handle_event(make_mouse_event(0, 0, true), event_phase::target);

            CHECK(target.down_count == 1);  // Inside bounds
        }

        SUBCASE("Just outside right edge") {
            target.handle_event(make_mouse_event(100, 25, true), event_phase::target);

            CHECK(target.down_count == 0);  // Outside bounds
        }

        SUBCASE("Just inside right edge") {
            target.handle_event(make_mouse_event(99, 25, true), event_phase::target);

            CHECK(target.down_count == 1);  // Inside bounds
        }
    }
}
