// Generated by CMake - DO NOT EDIT
// This file contains absolute paths to test data files needed by unit tests

#ifndef ONYXUI_TEST_CONFIG_HH
#define ONYXUI_TEST_CONFIG_HH

namespace test::config {

// Base directory for all test data files
inline constexpr const char* TESTDATA_DIR = "/home/igor/proj/ares/ui/unittest/testdata";

// Schema files directory
inline constexpr const char* SCHEMAS_DIR = "/home/igor/proj/ares/ui/unittest/testdata/schemas";

// Conio theme schema JSON file (used by test_json_schema.cc)
inline constexpr const char* CONIO_THEME_SCHEMA = "/home/igor/proj/ares/ui/unittest/testdata/schemas/conio_theme_schema.json";

// Example themes directory (used by test_directory_loading.cc and others)
inline constexpr const char* EXAMPLE_THEMES_DIR = "/home/igor/proj/ares/ui/themes";

} // namespace test::config

#endif // ONYXUI_TEST_CONFIG_HH
